Делает автоматическую сборку проекта, исправляет мелкие ошибки
htmlacademy-adaptive/1336871-cat-energy-24 pull request #11
Opened 2022-01-23 17:04 UTC by nadyayusova

Выполнено д/з №8: Написана автоматизация сборки проекта

2022-01-24 19:14 UTC, dean992008 requested changes

2022-01-24 19:14 UTC, dean992008 commented on package.json
> +    "del": "^6.0.0",
Версии зависимостей должны быть зафиксированы(в версии нужно быть `^`, `~` и т.д.)

2022-01-24 19:14 UTC, dean992008 commented on package.json
>    },
Скрипт `build` должен выполнять команду `gulp build`

2022-01-25 21:03 UTC, nadyayusova commented on package.json
> +    "del": "^6.0.0",
Убрала

2022-01-25 21:04 UTC, nadyayusova commented on package.json
>    },
Исправила

2022-01-26 16:04 UTC, merged