Создает разметку главной страницы
htmlacademy-adaptive/1336871-cat-energy-24 pull request #2
Opened 2021-11-27 21:53 UTC by nadyayusova

Выполнено д/з №2_1: сделана разметка главной страницы

2021-11-28 11:18 UTC, dean992008 requested changes

2021-11-28 11:18 UTC, dean992008 commented on source/index.html
> +        <a>
Лого должно состоять из 1 сылки. В сылку нужно полжить 2 картинки и потом скрыть 1 для планшета и десктопа, а для 2 использовать `picture`

2021-11-28 11:18 UTC, dean992008 commented on source/index.html
> +        <button class="main-nav__toggle" type="button" name="toggle-menu">
Нужно добавить `aria-label`

2021-11-28 11:18 UTC, dean992008 commented on source/index.html
> +      <h1 class="page-title__caption">Функциональное питание для котов</h1>
Думаю здесь лучше использовать h2, а h1 вынести первой строкой в main и скрыть с помощью visality-hidden. Также в h1 дучше сделать более точное описание тематики сайта, например "Интернет-магазин питания для котов".

2021-11-28 11:18 UTC, dean992008 commented on source/index.html
> +      <div class="diet-plan__slimming">
План питания я бы сделал отдельным блоком, так как теоретически он может переиспользоваться в других частях сайта.

2021-11-28 11:18 UTC, dean992008 commented on source/index.html
> +      <ol class="process__list">
Здесь правильнее использовать `ul` так как список не номерованый.

2021-11-28 11:18 UTC, dean992008 commented on source/index.html
> +      <div class="address">
Думаю здесь можно применить тег `address`

2021-11-28 11:18 UTC, dean992008 commented on source/index.html
> +        <iframe title="Карта с адресом компании Cat energy ул. Большая Конюшенная, 19/8" class="interactive-map"
Карту пока нужно вставить картинкой, потом реализуем через JS

2021-11-28 11:18 UTC, dean992008 commented on source/index.html
> +      <a class="logo-link" href="index.html">
Страница не должна везти сама на себя. Нужно удалить `href`

2021-11-28 11:18 UTC, dean992008 commented on source/index.html
> +          <a class="socials__link socials__link--vk" href="vk.com">
В ссылки который ведут на внешний спайт нужно добавить протокол(`http://` или `https://`) и добавить `target="_blank"`

2021-11-28 12:02 UTC, nadyayusova commented on source/index.html
> +          <a class="socials__link socials__link--vk" href="vk.com">
Добавила и добавила.

2021-11-28 12:03 UTC, nadyayusova commented on source/index.html
> +      <a class="logo-link" href="index.html">
Удалила.

2021-11-28 12:23 UTC, nadyayusova commented on source/index.html
> +        <iframe title="Карта с адресом компании Cat energy ул. Большая Конюшенная, 19/8" class="interactive-map"
Карту убрала.

2021-11-28 12:34 UTC, nadyayusova commented on source/index.html
> +      <div class="address">
Заменила на address.

2021-11-28 12:49 UTC, nadyayusova commented on source/index.html
> +      <ol class="process__list">
Заменила.

2021-11-28 13:16 UTC, nadyayusova commented on source/index.html
> +      <div class="diet-plan__slimming">
Действительно. Исправила.

2021-11-28 13:26 UTC, nadyayusova commented on source/index.html
> +      <h1 class="page-title__caption">Функциональное питание для котов</h1>
Исправила.

2021-11-28 14:33 UTC, nadyayusova commented on source/index.html
> +        <a>
Поместила 2 изображения в 1 ссылку.

2021-11-28 14:33 UTC, nadyayusova commented on source/index.html
> +        <button class="main-nav__toggle" type="button" name="toggle-menu">
Добавила.

2021-11-29 18:12 UTC, dean992008 commented on source/index.html
> +        <button class="main-nav__toggle" type="button" name="toggle-menu">
Это не исправлно. Нужно будет поправить вместе со следующим PR.

2021-11-29 18:12 UTC, merged