Выполняет детальную верстку главной страницы
htmlacademy-adaptive/1336871-cat-energy-24 pull request #7
Opened 2021-12-26 19:42 UTC by nadyayusova

Выполнено д/з №5_1: Декоративные элементы главной страницы

2021-12-27 07:49 UTC, dean992008 requested changes

2021-12-27 07:49 UTC, dean992008 commented on source/index.html
> +        <li class="process__item"><p class="process__text">Функциональное питание содержит только полезные питательные вещества.</p></li>
Этот блок я бы переделал. Здесь можно избавиться от грида. Я бы сделал на десктопе чтобы зеленая иконка была в потоке добавить ей `margin`, а цифру сделал бы абсолютом. 
На мобильном добавить паддинг с лева и зеленую иконку сделать абсолютом. 
`p` здесь вообще можно убрать.

2021-12-27 07:49 UTC, dean992008 commented on source/index.html
> +      <div class="map__inner container">
У карты не должно быть контейнера. Она должна тянуться на 100%. 
Также карту нужно будет переделать на js, чтобы была возможность сделать кастомный маркер. 
Вот пример: https://developers.google.com/maps/documentation/javascript/custom-markers?hl=en#maps_custom_markers-javascript

2021-12-27 07:49 UTC, dean992008 commented on source/index.html
> +        <div class="socials">
Этот div точно нужен?

2021-12-27 07:49 UTC, dean992008 commented on source/sass/blocks/button.scss
> +.button:active {
По возможности нужно использовать: https://up.htmlacademy.ru/adaptive/24/criteries#d11
К примеру здесь.

2021-12-29 19:02 UTC, nadyayusova commented on source/sass/blocks/button.scss
> +.button:active {
Посмотрела другие файлы, исправила. 
& забываю использовать.

2021-12-29 19:21 UTC, nadyayusova commented on source/index.html
> +        <div class="socials">
Это было для линии на мобильной версии. Див убрала, линию нарисовала нижнему блоку.

2021-12-29 20:54 UTC, nadyayusova commented on source/sass/blocks/button.scss
> +.button:active {
В main-nav есть сложные селекторы (состояния меню). Их не стала исправлять, т.к. сложно читаются.

2021-12-29 20:55 UTC, nadyayusova commented on source/index.html
> +        <li class="process__item"><p class="process__text">Функциональное питание содержит только полезные питательные вещества.</p></li>
Пока отложила, но хочу переделать.

2021-12-29 20:56 UTC, nadyayusova commented on source/index.html
> +      <div class="map__inner container">
Исправила.

2021-12-30 19:05 UTC, merged